// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using books452.Data;

#nullable disable

namespace books452.Migrations
{
    [DbContext(typeof(BooksDBContext))]
    [Migration("20240126111209_creatingCategoriesTableAndSeedingWithData")]
    partial class creatingCategoriesTableAndSeedingWithData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("books452.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Description = "This is the description for      the Travel category",
                            Name = "Travel"
                        },
                        new
                        {
                            CategoryId = 2,
                            Description = "This is the description for    the Fiction category",
                            Name = "Fiction"
                        },
                        new
                        {
                            CategoryId = 3,
                            Description = "This is the description        for the Technology category",
                            Name = "Technology"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
